stages:
  - test
  - build

variables:
  DOCKER_DRIVER: overlay2

test-auth-service:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - pytest auth_service/

test-note-service:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - pytest note_service/

test-api-gateway:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - pytest api_gateway/

build-docker-images:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker-compose build
  only:
    - main
